version: '3.7'

services:
  frontend:
    image: movies-info-frontend
    build:
      context: ./frontend
    environment:
      - NODE_ENV=development
      - TZ=America/Sao_Paulo
    volumes:
      - ./frontend:/usr/src/app
      - ./node_modules
    ports:
      - "8080:8080"
    command: http-server dist
    depends_on:
      - backend

    backend:
      image: movies-info-backend
      build:
        context: ./backend
      environment:
        - NODE_ENV=development
        - TZ=America/Sao_Paulo
      volumes:
        - ./backend:/usr/src/app
      ports:
        - "5000:5000"
      command: "gunicorn3 --bind 0.0.0.0:5000 run.py"
      depends_on: 
        - postgres

  postgres:
    image: postgres:10.8
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=movies_db
      - POSTGRES_USER=movies_user
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"

volumes:
  postgres:
    driver: local